# Generated by Django 5.1.1 on 2024-10-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='date_requested',
            new_name='request_date',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
